# Generated by Django 5.2.4 on 2025-10-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplan',
            name='knowledge_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], default='beginner'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('project', 'Project')], default='theory'),
        ),
    ]
