# Generated by Django 5.2.9 on 2025-12-04 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_plan', '0003_userprogress_time_spent_lessonnote_quiz_quizattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lessons_completed', models.IntegerField(default=0)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('notes_created', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0, help_text='Minutes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
